/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoestructuras1;

import javax.swing.ImageIcon;
import java.awt.Image;

/**
 * Formulario de Opciones principales del sistema.
 * @author PC_Mario
 */
public class frmOpciones extends javax.swing.JFrame {

    public frmOpciones() {
        initComponents();
        setLocationRelativeTo(null);
        cargarLogos();
    }

    private void cargarLogos() {
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo-vertical.png"));
            // Logo pequeño para la barra superior
            Image imgPeq = icon.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH);
            lblLogoHeader.setIcon(new ImageIcon(imgPeq));
            // Logo grande para el contenido central
            Image imgGrande = icon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
            lblLogoCentral.setIcon(new ImageIcon(imgGrande));
        } catch (Exception e) {
            lblLogoHeader.setText("UG");
            lblLogoCentral.setText("UNIVERSIDAD DE GUAYAQUIL");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblLogoHeader = new javax.swing.JLabel();
        lblTituloHeader = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        btnArreglos = new javax.swing.JButton();
        btnRecursividad = new javax.swing.JButton();
        btnOrdenamiento = new javax.swing.JButton();
        btnBusqueda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        lblLogoCentral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opciones - Proyecto Estructura de Datos");
        setPreferredSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(230, 236, 245));
        pnlHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(100, 160, 220)));
        pnlHeader.setPreferredSize(new java.awt.Dimension(900, 50));
        pnlHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 7));

        pnlHeader.add(lblLogoHeader);

        lblTituloHeader.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTituloHeader.setForeground(new java.awt.Color(20, 50, 100));
        lblTituloHeader.setText("PROYECTO DE ESTRUCTURA DE DATOS - OPCIONES");
        pnlHeader.add(lblTituloHeader);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlSidebar.setBackground(new java.awt.Color(230, 236, 245));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(165, 500));
        pnlSidebar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 15));

        btnArreglos.setBackground(new java.awt.Color(70, 130, 200));
        btnArreglos.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnArreglos.setForeground(new java.awt.Color(255, 255, 255));
        btnArreglos.setText("Arreglos");
        btnArreglos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArreglos.setPreferredSize(new java.awt.Dimension(140, 35));
        btnArreglos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArreglosActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnArreglos);

        btnRecursividad.setBackground(new java.awt.Color(70, 130, 200));
        btnRecursividad.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRecursividad.setForeground(new java.awt.Color(255, 255, 255));
        btnRecursividad.setText("Recursividad");
        btnRecursividad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecursividad.setPreferredSize(new java.awt.Dimension(140, 35));
        btnRecursividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecursividadActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnRecursividad);

        btnOrdenamiento.setBackground(new java.awt.Color(70, 130, 200));
        btnOrdenamiento.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnOrdenamiento.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenamiento.setText("Ordenamiento");
        btnOrdenamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdenamiento.setPreferredSize(new java.awt.Dimension(140, 35));
        btnOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenamientoActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnOrdenamiento);

        btnBusqueda.setBackground(new java.awt.Color(70, 130, 200));
        btnBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        btnBusqueda.setText("Búsqueda");
        btnBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusqueda.setPreferredSize(new java.awt.Dimension(140, 35));
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnBusqueda);

        btnSalir.setBackground(new java.awt.Color(70, 130, 200));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setPreferredSize(new java.awt.Dimension(140, 35));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlSidebar.add(btnSalir);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.WEST);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblLogoCentral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlContent.add(lblLogoCentral, new java.awt.GridBagConstraints());

        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArreglosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArreglosActionPerformed
        new frmArreglos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnArreglosActionPerformed

    private void btnRecursividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecursividadActionPerformed
        new frmRecursividad().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRecursividadActionPerformed

    private void btnOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenamientoActionPerformed
        new frmOrdenamiento().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrdenamientoActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        new frmBusqueda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        VehiculoService.getInstancia().limpiarTodo();
        new frmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArreglos;
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnOrdenamiento;
    private javax.swing.JButton btnRecursividad;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblLogoCentral;
    private javax.swing.JLabel lblLogoHeader;
    private javax.swing.JLabel lblTituloHeader;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlSidebar;
    // End of variables declaration//GEN-END:variables
}
